name = "discourse-utils"
main = "src/worker.tsx"
compatibility_date = "2024-02-21"
account_id = "95e065d2e3f97a1e50bae58aea71df6d"

[vars]
DEFAULT_RESPONSE = "Hi {original_poster}, your topic {has a solution here}.\n\nLet us know what you think of the solution by logging in and give it a :+1: or :-1:.\n\n---\n\nSolutions help the person that asked the question and anyone else that sees the answer later. Login to tell us what *you* think of the solution with a :+1: or :-1:."

[[kv_namespaces]]
binding = "CACHE"
id = "13fa0c8780974406888eed0e87d5ac6b"

[[queues.producers]]
queue = "answers"
binding = "QUEUE"

[[queues.consumers]]
queue = "answers"
