name = "discourse-utils"
main = "src/worker.ts"
compatibility_date = "2024-02-21"
account_id = "95e065d2e3f97a1e50bae58aea71df6d"

[[kv_namespaces]]
binding = "CACHE"
id = "13fa0c8780974406888eed0e87d5ac6b"

[[queues.producers]]
queue = "answers"
binding = "QUEUE"

[[queues.consumers]]
queue = "answers"
